### ISSUE TITLE
Table design revamp

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#6921]
### Is your proposal related to a problem?

Table awaits a well needed aesthetic revamp

### Describe the solution you'd like

Rework the UI/UX of the table component (and not the right side inspector), based on the figma file from design team.

[Figma design](https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign?type=design&node-id=324%3A85972&mode=design&t=xG2VyerVeM9HoElI-1)

For this iteration, only update the following items:

- [x] 1. New feature: Table header
- [x] 2. Table modules updates (new position and interaction)
  - [x]  1. Search
  - [ ]  2. Filter (consult with Jaseem for a few details)
  - [x]  3. Add new row
  - [x]  4. download
  - [x]  5. pagination (skip to ends: speak with Jaseem and Sherfin)
  - [x]  6. Manage columns
  - [x]  7. Number of records
- [x] 3. New type of loading state
- [ ] 4. New default data from the design file itself
- [x] 5. New design for scrollbars
- [x] 6. No-data state
- [x] 7. Row hovering and selection interaction
- [x] 8. Column header interactions
  - [x]  1. Sorting icons
- [ ] 9. Column position change interactions
- [x] 10. Column size change interactions
- [x] 11. Non-resizeable columns:
  - [x]   1.  Selector (checkboxes)
  - [x]   2.  Action buttons
- [x] 12. Editable column header icon
- [ ] 13. New type of filters: Discuss with Jaseem
- [x] 14. New table row style
- [x] 15. New table cell size

**Comment by sherfin94** [comment]
@manishkushare This does not cover the entirety of table design revamp, this covers only the major appearance updates of the component, we can do side panel as the next iteration

cc: @kavinvenkatachalam

**Comment by GrowwithNaveen** [comment]
This issue is closing in version 1.6. The following features will be completed:
1. Table demo data
2. Table column repositioning

Pending items have been documented in separate issues for future consideration.
1. Implementing enhanced table filtering functionality #9316
2. Implementing table density with refined UI #9325
