### ISSUE TITLE
Text component: Enhancement

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#7661]
### Required enhancements:

[Design file](https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=1502-665929&mode=design&t=iaeG56fwLCqUdNZE-0)
(Ignore elements in the design that are not described in the following checklist)

- [ ] Add new property that determines how the text is interpreted. This property can have three possible values: `plain text`, `markdown` and `HTML`. Check the design before implementation
- [ ] Next section should be events
- [ ] Next section should be titled `Additional options`, which contains
  - [ ] Loading state
  - [ ] Visibility
  - [ ] Disabled
  - [ ] Tooltip
- [ ] In the styles section, we need a new style called `Vertical alignment`, this should determine how the text content is vertically aligned within the component's area. Check the design.
- [ ] There is a new section called 'Container options' in the style tab, which has the following styles:
  - [ ] Background
  - [ ] Border color
  - [ ] Border radius (New style)
  - [ ] Box shadow
  - [ ] Padding (New style, check the design)
- [ ]  The order in which styles should be populated is the same as in the design
- [ ] New CSA called `clear` which sets the text of the component to empty string
- [ ] Three new CSAs:
  - [ ] `setVisibility`: same as the existing CSA called `visibility`, lets not display `visibility` in the inspector anymore, even though it should work
  - [ ] `setLoadingState`: allows setting loading state to either `true` or `false`
  - [ ] `setDisabled`: Allow disabling or enabling the component
- [ ] Three new exposed variables:
  - [ ] `isLoading`: returns the loading state
  - [ ] `isDisabled` : returns the disabled state
  - [ ] `isVisible` : returns the visibility state

**Comment by shakthi2003-ice** [comment]
Can you assign me this issue?

**Comment by sherfin94** [comment]
> Can you assign me this issue?

Hi @shakthi2003-ice , thank you for your offer to work on this. This particular issue however is a bit intricate and needs to be done internally.
