### ISSUE TITLE
Text input component enhancement

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#7998]
### Is your proposal related to a problem?

Text input component requires more aesthetic and functional improvements

### Describe the solution you'd like

- [ ] New property: `Label`
  - [ ] Label will have a default value: `Label`
- [ ] New property in validation section: `Mandatory`
  - [ ] If mandatory is turned on, then if the field is empty on `onBlur` of the field, there will be a validation error that says 'Field cannot be empty'
  - [ ] This will also show an asterisk(*) on the right side of the label
- [ ] Label styles on the styles sections (check design)
  - [ ] Alignment: Top or side (default to `Side`)
  - [ ] If `Side` is selected:
    - [ ] It can be aligned on the left side or the right side
    - [ ] The width of the label, with respect to the container can be set (default to 33%)
    - [ ]  If 'Auto width' is selected, then the width of the label increases with the label text that is supplied, upto a maximum of 70% (this is not selected by default)
- [ ] Field styles (check design)
  - [ ] New icon style
- [ ] Container styles (check design)
  - [ ] Padding: This is already needed in Text component, we can reuse from there.

Design: https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?node-id=1534%3A471781&mode=dev

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me
