### ISSUE TITLE
Table column type: Tags

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#8022]
### Is your proposal related to a problem?

The table column type 'Tags'  needs aesthetic improvements

### Describe the solution you'd like

[Design link](https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?node-id=1663%3A82830&mode=dev)

- [ ] Implement the design for:
  - [ ] Non-editable component
  - [ ] Editable component
- [ ] Column properties tab:
  - [ ] Implement as per design

#### Regarding backward compatibility

Notice that if `dynamic options` is selected, a single code-hinter asks for an array of objects. The existing `Dropdown` column actually asks for `keys` and `labels`, here, we need to make it so, that `key` and `label` are asked separately for dropdown columns in existing tables, and the new approach is only available in newly added tables.

**Comment by johnsoncherian** [comment]
Handled under issue: https://github.com/ToolJet/ToolJet/issues/8746
