### ISSUE TITLE
Table column type: Boolean

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#8023]
### Is your proposal related to a problem?

Table needs a boolean column type

PRD: [Click here](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-13876)

Figma Design: [Click here](https://www.figma.com/file/mnyECAMd6Wc7qRIDyYmYfI/Components-redesign-01?type=design&node-id=9564-278690&mode=design&t=EMrrIVQSSegaIgUJ-4)

### Describe the solution you'd like

- [ ] Implement the design for:
  - [ ] Non-editable component
  - [ ] Editable component
- [ ] Column properties tab:
  - [ ] Implement as per design

**Comment by GrowwithNaveen** [comment]
Duplicate item: [Boolean column type in table #6786](https://github.com/ToolJet/ToolJet/issues/6786)

**Comment by johnsoncherian** [comment]
Fixed in PR #9415
