### ISSUE TITLE
TJ DB: Expose SQL editor in Query builder for TJ DB data source

### ISSUE THREAD

**Issue by mansukh-tj** [ToolJet/ToolJet#9913]
PRD: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-24456)
ADR: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-22336)
Design: [link](https://www.figma.com/design/tYa0dxFKAObnxC8Jx0ACzn/TJ-DB?node-id=11875-135171&t=thbsg9SQvoTNcSM4-4)

**Problem:**
There is no means for a user to formulate SQL queries directly to query the underlying Postgres database when using TJDB

**Solution**
We need to be able to expose SQL interface where user can choose b/w GUI and SQL mode. Here GUI mode should be selected by default.

![Image](https://github.com/ToolJet/ToolJet/assets/11629675/6e19bb7b-8dc2-40af-9dc6-b823fcbe5f4c)

![Image](https://github.com/ToolJet/ToolJet/assets/11629675/07cd557a-805b-41f7-9dd2-c5fe2e94e0f3)

Tasks:

- [x] Implement the Frontend UI
- [x] Set up for PG users per workspace and data migration
- [x] The revised schema based user setup on Workspace setup flow - sync with Platform team
- [x] Make existing operations work with the new revised user setup. (Join + PostgREST operations)
- [ ] SQL execution with validations with test cases added
