### ISSUE TITLE
TJDB: As a user, I should be able to run aggregate functions with group by for TJDB queries

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9988]
PRD: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-22816) 
ADR: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-23416)

**Problem:**
Currently, there is no means to aggregate results in the query itself. User need to transform it separately to get the desired results.

**Solution**
In the existing - list rows and join tables operation - Aggregate will be shown as standalone operation just like sort and limit. In the first iteration, we will pick up only - Sum, and Count. 
In one query user will be able to add multiple aggregate conditions, corresponding to different columns.

**Limitations**
1. Sum can only be used for integer, big int and float data type 
2. Min and Max can be used for integer, big int, float and timestamp data types
3. Count will count all the values present in selected column except NULL  

**Subtasks:**
- [x] Add preliminary configuration setup for PostgREST
- [x] Update TJDB query manager for aggregate & group by in list query
- [x] Update for aggregate & group by in join query
