### ISSUE TITLE
TJDB: As a user, I should be able to store Date with time information

### ISSUE THREAD

**Issue by akshaysasidrn** [ToolJet/ToolJet#9989]
PRD: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-13756)
ADR: [link](https://app.clickup.com/37484951/v/dc/13qycq-2704/13qycq-23496)

**Problem:**
User is unable to add and edit time & date data using GUI into TJDB without converting it into a particular time format. Also, for primitive use cases of when the data entry was created or last edited users have to create manual entries.

**Solution:**
Enable GUI for adding and editing timestamp data fields with the flexibility to select the timezone of their preference
.
All timestamp datatype will store the details in UTC format. Upon rendering the UI, these fields will be converted to the user-selected timezone.
User will have the option to edit the Timezone in which he would like to view these fields

**Subtasks:**
- [x] Creating a wrapper component over react datetime picker as per design
- [x] Migrations for configurations
- [x] Support for date with time in dashboard
   - Create table 
   - View table
   - Edit row
   - Edit table
   - View table
   - Create column
   - Edit column
- [x] Support in Bulk upload
